[package]
name = "which"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive", "env"] }
libwhich = { workspace = true, features = ["tracing"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
